import { REACT_APP_API_HOST, REACT_APP_API_SCHEME, REACT_APP_API_PORT, REACT_APP_API_SUBPATH } from "@env"

console.log(REACT_APP_API_HOST, REACT_APP_API_SCHEME, REACT_APP_API_PORT, REACT_APP_API_SUBPATH)
export let shared = {
  env: {
    REACT_APP_DEBUG: '',
    REACT_APP_ISSUER: '',
    REACT_APP_CLIENT_ID: '',
    REACT_APP_API_SCHEME: REACT_APP_API_SCHEME || 'http',
    REACT_APP_API_HOST: REACT_APP_API_HOST || 'localhost',
    REACT_APP_API_PORT: REACT_APP_API_PORT,
    REACT_APP_API_SUBPATH: REACT_APP_API_SUBPATH || '/api'
  },
}